name: GitHub Actions - Cypress Tests
run-name: ${{ github.actor }} committed new code to the repository, executing Cypress tests
on: [push]
jobs:
  Execute-Cypress-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Cypress testing was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Testing is now running on a ${{ runner.os }} server hosted by GitHub"
      - run: echo "Current name of the branch being tested is ${{ github.ref }} for the repository ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "${{ github.repository }} repository has been cloned to the runner."
      - run: echo "Cypress testing is now ready to begin on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Cypress.io
        uses: cypress-io/github-action@v5.8.2
      - run: echo "Cypress tests status - ${{ job.status }}."
